### ISSUE TITLE
Crafting of the DragonSlayer Sword Requires Enderpearl with a Damage Value

### ISSUE THREAD

**Issue by AuricPolaris** [SpitefulFox/ForbiddenMagic#101]
Title says it all. Image below details the issue. Right clicking with a wand on a runic matrix will not start the infusion because of this ender pearl damage value.

http://imgur.com/CPgUYWh

Mod Version: Forbidden Magic-1.7.10-0.573
ModPack Used: FTB Infinity Expert Mode v2.4.2
KCauldron: KCauldron-1.7.10-1614.195-server

Let me know if you need any more information!

**Comment by SpitefulFox** [comment]
Thanks.  Already aware of it.  Haven't fixed it because the new Draconic Armor got patched to be immune to all weapons anyway.  Probably going to be removing the sword entirely if there's a new update to FM.

**Comment by AuricPolaris** [comment]
Ah, I see. Thank you for the quick reply and information. I was going to make it to fight the Ender Dragon or Chaos Guardian because 70 HP per hit looks exciting! If you do update FM for 1.7, could you perhaps leave it in but have it always be available for players to craft regardless of if DE is installed? I would love to use it just to fight the Ender Dragon. ^_^

**Comment by bookerthegeek** [comment]
removed? Sad. Why not instead just make it run /kill when hitting people in draconic/wyvern armour? That would be better. Would need to make the infusion a bit harder, but DE is slightly broken anyways.

**Comment by SpitefulFox** [comment]
/kill doesn't work on DE armor.  Nothing in the game works on DE armor as of the recent DE update.

I could find a way to make the sword work anyway, but then he can just come up with a new update to make it not work, and then I come up with a new update, etc... until one of us gets fed up and crashes the game and gets our own FTB Unhinged pack.

So, just removing the sword entirely.  If people are having problems with people using DE to bully in PvP, it's their fault for installing the mod.

**Comment by bookerthegeek** [comment]
Fully understand. Sad, but understandable.
