### ISSUE TITLE
infusion for silent dreamwood rod gives you gives dormant livingwood rod

### ISSUE THREAD

**Issue by DoomSquirter** [SpitefulFox/ForbiddenMagic#107]
latest, added to beyond reality classic pack.  thus, gregtech involved.

I assume if this was specific to FM, it would have been posted already since version is almost a year out there but I have to ask if this is something known or not.  

both infusions are identical but you swap the thing in the altar (livingwood vs dreamwood) but you get the livingwood version when you pull it out of the infusion.

this is on a server.

**Comment by SpitefulFox** [comment]
I've tested the recipe personally and it works fine even with several other mods installed.  The problem is with something in your pack.  I'm not gonna say it's definitely GregTech's fault, but I am going to give it some serious side-eye. >_>

**Comment by DoomSquirter** [comment]
thanks very much for prompt reply.  Appreciate it alot!
