### ISSUE TITLE
Forbidden Magic does not add any content for Botania

### ISSUE THREAD

**Issue by fullskele** [SpitefulFox/ForbiddenMagic#108]
In the Thaumonomicon I cannot find any Botania related items from Forbidden Magic, such as the Elementium caps or Dreamwood wand core. It can be seen from NEI, however it is impossible to create or view its creation.

This issue still persists even when using the latest versions of Thaumcraft, Botania, Baubles, and Forbidden Magic.

**Comment by SpitefulFox** [comment]
Make sure Botania content is enabled in the Forbidden Magic config.  Otherwise, check the game logs to see if there were any errors from Forbidden Magic.

**Comment by fullskele** [comment]
I checked the config to find out that the content from Botania was disabled for some reason. Thanks for the help, I appreciate that you are still taking care of this relatively outdated mod.
