### ISSUE TITLE
two potion effect and a sword

### ISSUE THREAD

**Issue by Twilight2** [SpitefulFox/ForbiddenMagic#111]
I am wandering about that what's the effect of blood seal and dragon wrack.Still,I didn't find the " dragon slayer" sword even I have installed twilight forest,drconic evolution , your forbidden magic and thaumcraft4 of course.
I leart the sword from here :https://m.ftbwiki.org/Sword_of_the_Dragonslayer

**Comment by Twilight2** [comment]
Well, I've found your answer about the sword,why not make it only as a weapon against dragons?Or make it cost a lot of DE armor's energy on hit(just like bloodrapier do)?
I do hope it will be add again, please!

**Comment by SpitefulFox** [comment]
I don't like trying to impose PvP balance across mods, so I won't be adding the item back in. If I were doing the mod again, I probably wouldn't add the Rapier of the Strix back in either.

Blood Seal is a debuff that prevents a player from adding LP to their soul network.
