### ISSUE TITLE
Impact enchant not working correctly with other mods

### ISSUE THREAD

**Issue by SpitefulFox** [SpitefulFox/ForbiddenMagic#25]
Reports are showing Impact not actually impacting.

**Comment by OldOpa** [comment]
I can confirm, Impact enchant is not working with Forbidden Magic-1.7.10-0.552.

**Comment by SpitefulFox** [comment]
That doesn't help me at all.  If I'm filing an issue myself, I don't need someone else to tell me that the issue exists.
