### ISSUE TITLE
Emerald Transmutation: No Output

### ISSUE THREAD

**Issue by stephen-smith** [SpitefulFox/ForbiddenMagic#33]
I'm playing Wanderlust Reloaded (version 1.2.0 for MC 1.7.10) and Forbidden Magic is included in the pack.

I tried to do emerald transmutation twice and both time my materials were consumed, but no output was generated.

First, 4x BoP sapphires (2x Vitreus, 2x Lucrum) in the crucible to generate aspects then 4x emerald fragments to catalyze the reaction.  No output.  No aspects remaining the the crucible.  Check: it's boiling.  The water level is a bit low; fill it up.

Okay, well, maybe sapphires didn't generate the right aspects or I did something else wrong.  So, I distilled out some pure Lucrum and Vitreus from glass and gold.  I drop in the phials and I see the aspects (8x Lucrum, 8x Vitreum) with my goggles.  I drop in an emerald fragment and 2x Lucrum and 2x Viteum disappear, but I don't see the output.  I try 3 more times (from various angles, with and without magnet mode), and am left with an crucible empty of aspects and even fewer emeralds than before.

https://github.com/Yulife/Wanderlust-Reloaded/blob/master/Server/config/ForbiddenMagic.cfg is the config.  I run the server and can confirm we haven't changed the configuration.

**Comment by SpitefulFox** [comment]
The recipe works just fine for me.  What mods are you using?

**Comment by SpitefulFox** [comment]
There's absolutely nothing in the code that's any different from the equivalent Thaumcraft recipes.  I'm unable to reproduce the problem and have no idea what could possibly cause it.  Sorry. :(
