### ISSUE TITLE
Localization changes needed

### ISSUE THREAD

**Issue by Adaptivity** [SpitefulFox/ForbiddenMagic#35]
1) Some tooltips(list.add) hardcoded. Notable: ItemBoundwell.java, ItemDivineOrb.java, ItemBloodwell.java.
2) Imprinted crystals localization should be changed. You should add something like %s tag to this line "item.MobCrystal.name=Imprinted Crystal". I need to swap mob name and Imprinted crystal. It should be something like Imprinted Crystal (Angry Zombie) instead of Angry Zombie Imprinted Crystal.

**Comment by SpitefulFox** [comment]
Thanks.  I'll try and get this fixed when I can.

**Comment by Adaptivity** [comment]
Can you reopen? Since point 2 still not implemented.

**Comment by SpitefulFox** [comment]
It is now.

**Comment by Adaptivity** [comment]
Thanks!
