### ISSUE TITLE
Shard unified wrongly when gregtech is existed

### ISSUE THREAD

**Issue by 3TUSK** [SpitefulFox/ForbiddenMagic#38]
Hello, I am in a server with forbidden magic 1.7.10-0.552 (with tc 4.2.3.0) and gregtech 5.06.06 (with ic2-experimental 2.2.658), and when a mob in nether drops some shards of forbidden magic, all of them will be converted into wrath shard or another certain kind of shard immediately. (it's impossible to know which shard they will convert into, for it is random)
All players in this server have the same problem. because of gregtech, i did investigate it, and the result is that gregtech detected that there is an OreDict "shardNether" include 7 shard (without tainted shard), then gt uses its own way to do such a unification on fm shard. If i remove gt, the problem will be solved.
i believe the problem is from OreDict, do you have some idea to fix it without removing any mod?
(due to some rules of gregtech, i think it's better to ask here first.)
thanks for your time.

**Comment by SpitefulFox** [comment]
All the shards are registered as shardNether so they can be used interchangeably in recipes.  Kind of like what GregTech does/did with circuits.  The problem is on GregTech's end for trying to force them all into one item.

**Comment by 3TUSK** [comment]
Well, here is a player in my server said that if there is a prefix "crafting" before "shardNether", which means the OreDict will be "craftingShardNether", the problem would be fixed.
He wants to know if you can do so, and he asked me to contact you.
Sorry for bothering you again.
PS I think MineTweaker can do this job
