### ISSUE TITLE
Suggestion: add an infusion recipie for Ars Magica 2 Affinity books

### ISSUE THREAD

**Issue by WolfAmaril** [SpitefulFox/ForbiddenMagic#41]
With AM2 getting closer and closer to it's final, stable release, it seems like the perfect time to add something like this!

**Comment by SpitefulFox** [comment]
Doesn't sound like a bad idea.  I'll consider it when the final release comes out.

In the meantime, I'm trying to focus on TC-only stuff.

**Comment by WolfAmaril** [comment]
Fair enough.
Though if I might add to the suggestion (having thought on it more)
Probably have them cost quite a bit, something like a full set of 8 essences of the type of book, and a few jars worth of essentia. Those things are pretty powerful and Mythion just said (over on the AM2 forum) that they're going to be basically restricted to boss drops in vanilla AM2

**Comment by SpitefulFox** [comment]
Oh.  Dunno if I wanna make recipes for them if they're gonna be boss drops. >.>
