### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by whitestarx0312** [SpitefulFox/ForbiddenMagic#44]
Using latest FM, and recommended 1.7.10 Forge.

Crash happens upon breaking with a Chameleon Pickaxe.

http://pastebin.com/9H4Ltjr1

**Comment by whitestarx0312** [comment]
On a side note, it doesn't drop some of the items it breaks when it crashes, and sometimes when you break certain items. For instance, the game crashed while I was breaking a power spawner and attractor from EnderIO. These items did not drop on the ground.

**Comment by whitestarx0312** [comment]
The crash still happens, it just doesn't delete items

**Comment by SpitefulFox** [comment]
Chameleon Pickaxe is already re-written for the next patch.
