### ISSUE TITLE
Shard generation is malfunctioning.

### ISSUE THREAD

**Issue by Dream-Master** [SpitefulFox/ForbiddenMagic#46]
Mobs only dropping wrath shards. Tested with : 

ForbiddenMagic 0.552
BloodMagic 1.3.0b-3 and 
Thaumcraft 4.2.3.4
Witchery 0.22.0

**Comment by SpitefulFox** [comment]
Mobs only dropping wrath shards when you kill them?  Even the pigmen with the envy shards?  Or are you just killing mobs in general and only seeing wrath shards?  Wrath shards drop from killing.  The other shards have specific circumstances.

**Comment by Dream-Master** [comment]
I try now with fresh config files and i get only pride shards.

**Comment by Drobac** [comment]
Pigmen with envy shard either drop nothing or wrath shards. Also tried hitting everything imaginable with the riding crop and no lust shards. Also no shards from passive killing

**Comment by SpitefulFox** [comment]
Are you using GregTech?

**Comment by Dream-Master** [comment]
Yes

**Comment by SpitefulFox** [comment]
That's why.

**Comment by Drobac** [comment]
worked on an earlier version with gregtech normally

**Comment by Dream-Master** [comment]
Can you explain why it not working ?

**Comment by SpitefulFox** [comment]
GregTech messes with items that don't use the Ore Dictionary in ways that he likes.

**Comment by Dream-Master** [comment]
Ordicted this shards with minetweaker not change any thing ?

**Comment by Dream-Master** [comment]
Otherwise i can make Modtweaker Infusion recipes to get those shards.
