### ISSUE TITLE
Plea of delayed insanity ritual crash

### ISSUE THREAD

**Issue by ChatFawkes** [SpitefulFox/ForbiddenMagic#52]
Forbidden Magic version: 0.56
Blood Magic Version: 1.3.0b-3
Thaumcraft Version: 4.2.3.5

Crash when happens when a player on the server tries to use the ritual. Didn't do it myself, so if more info is needed I can ask him to provide it.

[Crash Report](https://gist.github.com/ChatFawkes/7e67152062f750e80182)

**Comment by SpitefulFox** [comment]
I see what happened there.  I'll get that fixed in the next patch.  Thanks for the report.
