### ISSUE TITLE
Crystal Scribing Tools cannot be craft due to missing vis cost

### ISSUE THREAD

**Issue by ewsmith** [SpitefulFox/ForbiddenMagic#54]
The crystal scribing tools can't be craft because the recipe calls for absolutely nada from your wand.

src/main/java/fox/spiteful/forbidden/ForbiddenRecipes.java
```java
ForbiddenResearch.recipes.put("Crystalwell", ThaumcraftApi.addShapelessArcaneCraftingRecipe("CRYSTALWELL", new ItemStack(ForbiddenItems.crystalwell, 1, 0), (new AspectList()), new Object[] { new ItemStack(ConfigItems.itemInkwell, 1, 32767), "dyeBlack", new ItemStack(ConfigItems.itemShard, 1, 32767), new ItemStack(ConfigItems.itemShard, 1, 32767) }));
```

the `(new AspectList())` has no aspects tied to it.

**Comment by SpitefulFox** [comment]
Ugh.  Knew I forgot to test something.

You'd think TC would be able to handle something like that, but nooooooo.

Thanks for the report.
