### ISSUE TITLE
Ars magica 2 compat

### ISSUE THREAD

**Issue by HardInk** [SpitefulFox/ForbiddenMagic#57]
Forbidden magic and ars magica are having a hard time playing nice with each other. It seems that I cant get forbidden magic to allow for witchwood cores or vinteum caps with AM2 installed. I'm haven't been able to find a player beacons version with 1.7.10 that doesn't crash so I haven't checked compat with those parts. 
Versions
AM2 1.4.0.008
Forbidden Magic 1.7.10-0.561
Thaumcraft 4.2.3.5

**Comment by SpitefulFox** [comment]
Go into the FM config.  Enable AM2 interaction.
