### ISSUE TITLE
[Suggestion] Disable Enchantments

### ISSUE THREAD

**Issue by T4ge** [SpitefulFox/ForbiddenMagic#58]
Title pretty much explains it, I want to be able to disable each enchant if possible, but mainly the Wrath enchantment as it breaks the current balance of my pack if this is possible.

**Comment by Vazkii** [comment]
Use modtweaker to remove the entries.

**Comment by SpitefulFox** [comment]
Sorry.  I'm not going to be implementing configs for each and every little aspect of my mod.  If you're really in dire need of removing things, use Modtweaker like Vazkii suggested.

**Comment by T4ge** [comment]
Thanks guys, I'll look into it, shouldve thought about that!
