### ISSUE TITLE
[Bug] Elementium kissed Dreamwood Wand fully draining nodes 

### ISSUE THREAD

**Issue by kenny2810** [SpitefulFox/ForbiddenMagic#60]
Type: Bug
Problem: Elementium kissed Dreamwood  Wand are fuly draining nodes 

Description: I have EVERY research (and I do mean every). After I finally managed to make the wand, I went to start to fill it and found that it acted same as an iron capped normal wand in that it fully drained nodes leaving nothing. Since only the iron capped one is supposed to do this, I assumed its a bug.

**Comment by SpitefulFox** [comment]
Don't sneak when draining nodes.
