### ISSUE TITLE
Mod Compat: Allow Thaumic Cake to be consumed by Kekimurus?

### ISSUE THREAD

**Issue by jngeist** [SpitefulFox/ForbiddenMagic#67]
I've just checked on the source over at Botania, and all the Kek does is check if a nearby block subclasses Minecraft's BlockCake. I don't know my way around the base Minecraft classes at all, but if it were possible to make ArcaneCake subclass BlockCake instead of Block, it'd make for some really interesting vis/mana interactions.

**Comment by SpitefulFox** [comment]
After some testing, it appears that the Kekimurus eats the Thaumic Cake faster than it can regenerate.  Furthermore, the Kekimurus is hardcoded to assume cakes have 7 bites, so it finishes the Thaumic Cake when there's still lots of cake left.

Unfortunately, this means there's little to no advantage in using a Thaumic Cake over a regular one.  So, gonna leave it inedible by the Kekimurus.
