### ISSUE TITLE
incompatability with artifice.

### ISSUE THREAD

**Issue by klikkolee** [SpitefulFox/ForbiddenMagic#76]
installing artifice 1.7.10-1.1.5r-396 and forbidden magic 1.7.10-0.562, their dependences(cofh core [1.7.10] 3.0.2-262, thaumcraft 1.7.10-4.2.3.5, and forge 10.13.4.1448-1.7.10) causes minecraft to crash before reaching the title screen. [here is the crash report.](https://drive.google.com/file/d/0B6SAipjmm0FiY3lYYm9ZUndFY3M/view?usp=sharing) I have also tried a few permutations of mod versions without effect. Of note is that I am using a machine running Ubuntu 14.04 and Java 8

This was created in an install specifically to investigate this incompatibility and as such contains no mods besides what is listed above. I do apologise if you prefer a different venue for bug reports; the forum thread was non-specific in this regard.

**Comment by SpitefulFox** [comment]
As the first line of the error suggests, you have an enchantment ID conflict.  Go into the configs and change the IDs to not match each other.  You can use NEI to save a list of unused enchantment IDs if you don't know what to change the IDs to.

**Comment by klikkolee** [comment]
ah. for some reason, "invalid argument" made me think "type mismatch" which would have warranted this post. I do apologise
