### ISSUE TITLE
Ring of Nutrition breaking Hunger Overhaul

### ISSUE THREAD

**Issue by PK-Antifreeze** [SpitefulFox/ForbiddenMagic#78]
Hunger Overhaul changes many vanilla food values, but Forbidden Magic ignores it and adds onto the vanilla values. An example is a carrot, where without the ring it gives 1/2 hunger and ~1/2 saturation and with the ring it gives 1 1/2 hunger and 4 saturation.

Asking elsewhere, it seems that checking for AppleCore and basing nutrition values off of that is a method for cross-mod support. Is there any way this can be implemented?

**Comment by SpitefulFox** [comment]
Forbidden Magic doesn't add based on vanilla values.  It adds the exact same flat value whether a food is worth 8 shanks or .5 shanks.

If ring of nutrition is inappropriate for the pack you're playing, disable it with the gluttony config.
