### ISSUE TITLE
Update Forbidden Magic's BM support

### ISSUE THREAD

**Issue by Arcaratus** [SpitefulFox/ForbiddenMagic#79]
Looking through the code, and I see some stuff is pretty outdated with the current version of BM. The orb is completely out of date, and some things in the API have updated; if you'd like, I'll do a pull request if you're too busy

**Comment by SpitefulFox** [comment]
Hm?  What's wrong with stuff? o.O

**Comment by Arcaratus** [comment]
The blood orb for instance, allows the user to reach 80mil with only the orb, not others (causes problems when things call for max LP a soul network can store) it also only subtracts 1 health in a non-updated fashion. (See here: 
https://github.com/WayofTime/BloodMagic/blob/master/src/main/java/WayofTime/alchemicalWizardry/common/items/EnergyBattery.java#L93-L94)

**Comment by SpitefulFox** [comment]
>.<

He didn't have all these things when I wrote the orb.

**Comment by Arcaratus** [comment]
Which is why I said update :P
