### ISSUE TITLE
Forbidden magic crashes

### ISSUE THREAD

**Issue by DrLivingstones** [SpitefulFox/ForbiddenMagic#82]
I'm having an issue where Forbidden Magic crashes when trying to start a world. Here is the crash report http://puu.sh/jotpW/45e27751fa.txt Think it might be an enchantment conflict with artifice but im not too sure how to fix that

**Comment by SpitefulFox** [comment]
As the crash report says at the very top, you have a duplicate enchantment ID.  Go into the configs and change either the Artifice enchant IDs or FM's.

**Comment by DrLivingstones** [comment]
Changed an Artifice ID and now I got this http://puu.sh/joA2g/38ac531f3f.txt
