### ISSUE TITLE
[Suggestion] Stick your baubles into Botania's "cosmetic" system

### ISSUE THREAD

**Issue by Azutte** [SpitefulFox/ForbiddenMagic#94]
Rather, let them have cosmetic overrides. Mostly I am just imagining still being able to wear my Red Glasses, but it's secretly actually a Collar of Pain.

**Comment by diamondjbj2** [comment]
Sounds good.  Will try and make this a thing.

Having a kinky collar appear on the character also sounds appealing. x3

**Comment by SpitefulFox** [comment]
Sounds good.  Will try and make this happen.

Having a kinky collar model for the collar sounds good too. x3
