### ISSUE TITLE
Crystal Scribing Tool Bug

### ISSUE THREAD

**Issue by Surphis** [SpitefulFox/ForbiddenMagic#97]
Under 0.572 of Forbidden Magic for 1.7.10, I noticed when I crafted a second set of Crystal Scribing Tools that I received about twice as many research points when both were in my inventory.  Decided to launch a creative world and filled my inventory with them, and sure enough, I had 400 research points in about 3-4 minutes.

I'm guessing this is not intended functionality since it's ripe for abuse so I decided to hunt down the github and post.

I should probably mention that this functionality of the scribing tools is only available when Thaumcraft research is set to easy.  Forgot to post that initially.

**Comment by SpitefulFox** [comment]
That's the intended functionality when research is set to easy.  Guess I can look into putting some sort of limit on filling your inventory with them.

**Comment by Surphis** [comment]
I figured that the tools weren't intended to stack the return based on the number of them in your inventory.  If that is intended, than this is more of a balance concern than a bug and I realize how subjective balance can be.

If this is balance, maybe having a config option for the amount of research points returned or the number of ticks before the event handler fires would allow users to adjust to their preference.
